### ISSUE TITLE
Can't connect from other docker container

### ISSUE THREAD

**Issue by niclashoyer** [Painted-Fox/docker-mariadb#8]
If I try to connect from another docker container I get

```
SQLSTATE[HY000] [1130] Host '172.17.0.4' is not allowed to connect to this MariaDB server
```

I see that there is the following in `first_run.sh`:

```
CREATE USER '$USER'@'%' IDENTIFIED BY '$PASS';
GRANT ALL PRIVILEGES ON *.* TO '$USER'@'%' WITH GRANT OPTION;
```

so it should be working. Any idea why I get this error? Is there something I could check?

**EDIT**:
Using `docker logs` I get:

```
MARIADB_USER=super
MARIADB_PASS=LlEZm86IxY0SXLNt
MARIADB_DATA_DIR=/data
Initializing MariaDB at /data
Starting MariaDB...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)
140306 22:26:33 mysqld_safe Logging to '/data/mysql.log'.
140306 22:26:33 mysqld_safe Starting mysqld daemon with databases from /data
```

Maybe the error in between is the problem?

**Comment by Painted-Fox** [comment]
Hi @niclashoyer.  Thank you for submitting this bug report!

This error:

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)
```

...looks like it comes from the `first_run.sh` when it tries to first run some SQL.  I've seen this error in the log while the mysql client tries to connect to the server while the server is initializing and not accepting connections yet.  In the `start.sh` script, the function `wait_for_mysql_and_run_post_start_action()` will wait for the socket to _exist_ before executing the other script.

I don't think this error message is the problem, but are you able to reproduce it consistently?

Could you tell me how you're starting the MariaDB container and the linked  container?

Also, could you try connecting to MariaDB with the mysql client command from the linked container?  I tried this and found that the command in the documentation is wrong, but I am able to connect to MariaDB.  Here's what I did:

```
fox@Squeak:~/proj$ docker run -d -name=mariadb -p 127.0.0.1:3306:3306 -v /srv/docker/mariadb:/data -e USER=super -e PASS=r0JsGTSBbFyVJGMN paintedfox/mariadb
516998c29ce1e126289311234b9fa570181f98174c720f45dbe456dba55fcd0a
fox@Squeak:~/proj$ docker logs mariadb
MARIADB_USER=super
MARIADB_PASS=r0JsGTSBbFyVJGMN
MARIADB_DATA_DIR=/data
Starting MariaDB...
140307 03:29:23 mysqld_safe Logging to '/data/mysql.log'.
140307 03:29:23 mysqld_safe Starting mysqld daemon with databases from /data
fox@Squeak:~/proj$ docker run -t -i -link mariadb:db ubuntu bash
root@4a84f17c60e2:/# apt-get install -y mysql-client
Reading package lists... Done
Building dependency tree... Done
[...]
root@4a84f17c60e2:/# mysql -u 'super' --password='r0JsGTSBbFyVJGMN' -h "$DB_PORT_3306_TCP_ADDR" -P "$DB_PORT_3306_TCP_PORT"
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 4
Server version: 5.5.34-MariaDB-1~precise-log mariadb.org binary distribution

Copyright (c) 2000, 2011, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

**Comment by niclashoyer** [comment]
Thank you for the fast reply. I just wanted to let you know that I'll try your suggestions in the next days. I'm a bit busy at the moment.

**Comment by Painted-Fox** [comment]
No problem.  I keep myself pretty busy, so I understand.

**Comment by niclashoyer** [comment]
Sorry for the delay. I can't reproduce it anymore, so closing.
